### ISSUE TITLE
Failed to import CuPy

### ISSUE THREAD

**Issue by alexfredo** [zyddnys/sd_animation_optical_flow#1]
Hi I have install cupy but when I try to execute for example "py ofgen_pixel_inpaint.py --i 1.mp4 --o C:\AUTOMATIC1111\SDOPTICALFLOW\save_dir\1.mp4"

I have this error :
 warnings.warn(f'''
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\cuda\compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: Le module spécifié est introuvable.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\ofgen_pixel_inpaint.py", line 17, in <module>
    from pdcnet_of import warp_frame_latent as warp_frame_latent_pdcnet, warp_frame as warp_frame_pdcnet
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\pdcnet_of.py", line 8, in <module>
    from models.PDCNet.PDCNet import PDCNet_vgg16
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\models\PDCNet\PDCNet.py", line 8, in <module>
    from models.modules.local_correlation import correlation
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\models\modules\local_correlation\correlation.py", line 3, in <module>
    import cupy
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: DLL load failed while importing runtime: Le module spécifié est introuvable.
================================================================

**Comment by alexfredo** [comment]
I fixed the error but now I have another bug : 
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\ofgen_pixel_inpaint.py", line 17, in <module>
    from pdcnet_of import warp_frame_latent as warp_frame_latent_pdcnet, warp_frame as warp_frame_pdcnet
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\pdcnet_of.py", line 8, in <module>
    from models.PDCNet.PDCNet import PDCNet_vgg16
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\models\PDCNet\PDCNet.py", line 8, in <module>
    from models.modules.local_correlation import correlation
  File "C:\AUTOMATIC1111\SDOPTICALFLOW\models\modules\local_correlation\correlation.py", line 278, in <module>
    @cupyutil.memoize(for_each_device=True)
AttributeError: module 'cupy' has no attribute 'memoize'

**Comment by alexfredo** [comment]
What version of cupy I need to install ? thanks

**Comment by zyddnys** [comment]
I use cupy==11.6.0 on Linux machine, don't know if it works on windows
